// ----------------------------------------------------------------------------
//  seedLibrary.ts - the hand-written Slice 1 template library
//  (template-model/02-seed-library).
//
//  This is QuibbleStone's tiny, hand-curated content library (README section
//  4 / 7 / 8 - "a tiny hand-written library" is part of the thin vertical
//  slice). Every entry is a plain `Template` object literal built with the
//  `text()` / `blank()` constructors exported from `../engine/template`
//  (template-model/01). This file is PURE DATA - no AI generation, no
//  authoring UI, no back-office content factory (those are explicitly out of
//  scope here; see docs/features/template-model/02-authoring-and-seed-library.md). Adding a
//  new template is a single, documented step: append one object literal to
//  `seedLibrary` below. See ./README.md for the full authoring guide and a
//  copy-paste starter template.
//
//  Child safety (README section 6): every template here is tagged
//  `tags.familySafe = true` / `tags.ageRating = 'all-ages'` and has been
//  hand-vetted to the SAME bar a player's submitted word must clear at play
//  time (the runtime profanity/safety filter, owned by child-safety/01, is a
//  separate complementary guard for player-submitted free text - this file
//  does not reimplement it; it just makes sure the seed content itself never
//  needs filtering). The humor here comes from absurdity (talking llamas,
//  carsick aliens, a sock-eating dragon), never from innuendo or edge.
//
//  Who imports this: single-player and group-play (the template picker
//  reads this array today; later it can move behind the API / Table Storage
//  without changing the shape - see the file footer note in ./README.md).
// ----------------------------------------------------------------------------

import { blank, text, type Template } from '../engine/template';

export const seedLibrary: readonly Template[] = [
  {
    id: 'wobbly-wizard',
    title: 'The Wobbly Wizard & the Golden Sock',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['fantasy', 'monsters'] },
    body: [
      text('Once upon a time, a '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes a person or thing - anything goes!',
        sparkWords: ['wobbly', 'sparkly', 'enormous'],
      }),
      text(' wizard named '),
      blank({
        id: 'b2',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our hero.',
        sparkWords: ['Bartholomew', 'Pickle', 'Zorbo'],
      }),
      text(' lost a magic '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Any object, big or small.',
        sparkWords: ['sock', 'spoon', 'hat'],
      }),
      text('. To find it, they had to '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['waddle', 'juggle', 'sneeze'],
      }),
      text(' all the way to the top of a '),
      blank({
        id: 'b5',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['mountain', 'castle', 'broom closet'],
      }),
      text('. '),
      blank({
        id: 'b6',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'An exclamation, like "Yikes!" or "Hooray!"',
        sparkWords: ['Yowza!', 'Holy moly!', 'Ta-da!'],
      }),
      text(' they cried, and the sock was found at last.'),
    ],
  },
  {
    id: 'space-llama',
    title: 'The Space Llama Who Forgot His Helmet',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['space', 'animals'] },
    body: [
      text('Captain '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our space traveler.',
        sparkWords: ['Nibbles', 'Captain Fuzz', 'Dottie'],
      }),
      text(' the llama blasted off in a '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the rocket.',
        sparkWords: ['squeaky', 'glittery', 'lopsided'],
      }),
      text(' rocket made of '),
      blank({
        id: 'b3',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "marshmallows".',
        sparkWords: ['marshmallows', 'bottle caps', 'noodles'],
      }),
      text('. Halfway to the moon, the llama began to '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['hiccup', 'somersault', 'hum'],
      }),
      text(' because there were '),
      blank({
        id: 'b5',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['7', '42', '1,000'],
      }),
      text(' space goats staring through the window.'),
    ],
  },
  {
    id: 'road-trip-disaster',
    title: 'The Great Family Road Trip Disaster',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['road-trip', 'family'] },
    body: [
      text('We packed the car with '),
      blank({
        id: 'b1',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['12', '300', '3'],
      }),
      text(' bags of '),
      blank({
        id: 'b2',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "snacks".',
        sparkWords: ['pretzels', 'rubber ducks', 'socks'],
      }),
      text(' and drove toward '),
      blank({
        id: 'b3',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ["Grandma's house", 'the moon', 'Pancake City'],
      }),
      text('. Halfway there, Dad started to '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['yodel', 'wiggle', 'snore'],
      }),
      text(' so loudly that everyone shouted "'),
      blank({
        id: 'b5',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'An exclamation, like "Whoa!" or "Pull over!"',
        sparkWords: ['Whoa!', 'Pull over!', 'My ears!'],
      }),
      text('"'),
    ],
    // Every blank category in this template (number, plural-noun, place, verb,
    // exclamation) has bank entries, so Word Bank mode always has words to tap
    // on every blank - see seedLibrary.test.ts's coverage guard.
    wordBank: [
      { category: 'number', word: '12' },
      { category: 'number', word: '300' },
      { category: 'number', word: '7' },
      { category: 'plural-noun', word: 'pretzels' },
      { category: 'plural-noun', word: 'rubber ducks' },
      { category: 'plural-noun', word: 'socks' },
      { category: 'place', word: 'Pancake City' },
      { category: 'place', word: "Grandma's house" },
      { category: 'place', word: 'the moon' },
      { category: 'verb', word: 'yodel' },
      { category: 'verb', word: 'wiggle' },
      { category: 'verb', word: 'snore' },
      { category: 'exclamation', word: 'Whoa!' },
      { category: 'exclamation', word: 'Pull over!' },
      { category: 'exclamation', word: 'My ears!' },
    ],
  },
  {
    id: 'school-of-noodles',
    title: 'Show and Tell at Noodle Elementary',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['school'] },
    body: [
      text('At school today, '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our classmate.',
        sparkWords: ['Pip', 'Waffles', 'Mortimer'],
      }),
      text(' brought a '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the thing they brought.',
        sparkWords: ['squishy', 'invisible', 'humongous'],
      }),
      text(' '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Any object, big or small.',
        sparkWords: ['kazoo', 'pet rock', 'umbrella'],
      }),
      text(' for show and tell. When asked to explain it, they started to '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['tap-dance', 'whistle', 'cartwheel'],
      }),
      text(' instead, and the whole class clapped.'),
    ],
  },
  {
    id: 'monster-under-bed',
    title: 'The Monster Under the Bed Needs a Favor',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['monsters'] },
    body: [
      text('Under the bed lived a '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the monster.',
        sparkWords: ['fluffy', 'three-eyed', 'ticklish'],
      }),
      text(' monster named '),
      blank({
        id: 'b2',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our monster.',
        sparkWords: ['Glorp', 'Bubbles', 'Sir Fang'],
      }),
      text(' who really needed to borrow a '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Any object, big or small.',
        sparkWords: ['flashlight', 'pillow', 'banana'],
      }),
      text('. Every night it would '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['tiptoe', 'giggle', 'tumble'],
      }),
      text(' around the room looking for one.'),
    ],
  },
  {
    id: 'food-truck-frenzy',
    title: 'Grand Opening of the Mystery Food Truck',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['food'] },
    body: [
      text('The new food truck served '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the food.',
        sparkWords: ['gooey', 'rainbow', 'crunchy'],
      }),
      text(' '),
      blank({
        id: 'b2',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "pancakes".',
        sparkWords: ['pancakes', 'tacos', 'meatballs'],
      }),
      text(' topped with '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Any topping you can imagine.',
        sparkWords: ['glitter', 'cheese', 'confetti'],
      }),
      text('. The line stretched all the way to '),
      blank({
        id: 'b4',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['the library', 'outer space', 'next door'],
      }),
      text(', and everyone agreed it was the best lunch ever.'),
    ],
    // Every blank category in this template (adjective, plural-noun, noun,
    // place) has bank entries, so Word Bank mode always has words to tap on
    // every blank - see seedLibrary.test.ts's coverage guard.
    wordBank: [
      { category: 'adjective', word: 'gooey' },
      { category: 'adjective', word: 'rainbow' },
      { category: 'adjective', word: 'crunchy' },
      { category: 'plural-noun', word: 'pancakes' },
      { category: 'plural-noun', word: 'tacos' },
      { category: 'plural-noun', word: 'meatballs' },
      { category: 'noun', word: 'cheese' },
      { category: 'noun', word: 'glitter' },
      { category: 'noun', word: 'confetti' },
      { category: 'place', word: 'the library' },
      { category: 'place', word: 'outer space' },
      { category: 'place', word: 'next door' },
    ],
  },
  {
    id: 'backyard-safari',
    title: 'The Backyard Safari Expedition',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['animals'] },
    body: [
      text('Armed with a magnifying glass, '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our explorer.',
        sparkWords: ['Indy', 'Professor Pebbles', 'Marisol'],
      }),
      text(' set off to find the rare and '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the creature.',
        sparkWords: ['polka-dotted', 'extremely shy', 'bouncy'],
      }),
      text(' backyard '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me an animal or creature',
        subHint: 'Any critter, real or made up.',
        sparkWords: ['snail', 'squirrel', 'dragonfly'],
      }),
      text('. After hours of searching, it was finally spotted - and it began to '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['wave', 'nap', 'do a backflip'],
      }),
      text(' right on cue.'),
    ],
  },
  {
    id: 'pirate-puddle',
    title: 'Captain Puddlebeard and the Bathtub Treasure',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['pirates', 'fantasy'] },
    body: [
      text('Ahoy! Captain '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our captain.',
        sparkWords: ['Puddlebeard', 'Salty Sam', 'Coral'],
      }),
      text(' sailed the seven bathtubs in search of a '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the treasure.',
        sparkWords: ['shimmering', 'rubbery', 'gigantic'],
      }),
      text(' chest of '),
      blank({
        id: 'b3',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "gummy bears".',
        sparkWords: ['gummy bears', 'bath toys', 'bubbles'],
      }),
      text('. To claim it, the crew had to '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['splash', 'sing', 'paddle'],
      }),
      text(' past the dreaded Soap Kraken. "'),
      blank({
        id: 'b5',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'An exclamation, like "Arr!" or "Land ho!"',
        sparkWords: ['Arr!', 'Land ho!', 'Splashtastic!'],
      }),
      text('" the captain bellowed.'),
    ],
  },
  {
    id: 'robot-recital',
    title: 'The Robot Who Joined the School Talent Show',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['school', 'sci-fi'] },
    body: [
      text('A '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the robot.',
        sparkWords: ['clanky', 'shiny', 'tiny'],
      }),
      text(' robot named '),
      blank({
        id: 'b2',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our robot.',
        sparkWords: ['Beep-Bop', 'Gearald', 'Sprocket'],
      }),
      text(' signed up to '),
      blank({
        id: 'b3',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO on stage.',
        sparkWords: ['tap-dance', 'juggle', 'yodel'],
      }),
      text(' in front of the whole school. Instead, it short-circuited and shot '),
      blank({
        id: 'b4',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['50', '6', '999'],
      }),
      text(' confetti '),
      blank({
        id: 'b5',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "sparks".',
        sparkWords: ['sparks', 'bolts', 'balloons'],
      }),
      text(' into the air, and everyone gave a standing ovation anyway.'),
    ],
  },
  {
    id: 'dragon-sock-thief',
    title: 'The Dragon Who Only Eats Mismatched Socks',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['monsters', 'fantasy'] },
    body: [
      text('Deep in a '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the cave.',
        sparkWords: ['cozy', 'sparkly', 'squeaky'],
      }),
      text(' cave lived a dragon who only ate mismatched '),
      blank({
        id: 'b2',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "socks".',
        sparkWords: ['socks', 'mittens', 'flip-flops'],
      }),
      text('. Every night it would sneak into '),
      blank({
        id: 'b3',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['the laundry room', 'a sleepover', 'the dryer'],
      }),
      text(' and '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['tiptoe', 'sniff around', 'pounce'],
      }),
      text(' until it found a tasty pair. "'),
      blank({
        id: 'b5',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'An exclamation, like "Yum!" or "Found one!"',
        sparkWords: ['Yum!', 'Found one!', 'Sock-tastic!'],
      }),
      text('" it would rumble happily.'),
    ],
  },
  {
    id: 'birthday-balloon-mayhem',
    title: 'The Birthday Party That Floated Away',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['family', 'birthday'] },
    body: [
      text('At '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our birthday star.',
        sparkWords: ['Sunny', 'Biscuit', 'Theo'],
      }),
      text("'s birthday party, someone brought "),
      blank({
        id: 'b2',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['1,000', '15', '88'],
      }),
      text(' '),
      blank({
        id: 'b3',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the balloons.',
        sparkWords: ['enormous', 'squeaky', 'glittery'],
      }),
      text(' balloons. They were tied to the cake, but the wind began to '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['whistle', 'swirl', 'tug'],
      }),
      text(', and the whole cake floated off toward '),
      blank({
        id: 'b5',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['the treetops', 'the moon', 'next door'],
      }),
      text('.'),
    ],
  },
  {
    id: 'snowman-summer-job',
    title: 'The Snowman Who Got a Summer Job',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['seasons', 'monsters'] },
    body: [
      text('When the snow melted, '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our snowman.',
        sparkWords: ['Frosty Jr.', 'Chilly', 'Sir Slush'],
      }),
      text(' the snowman refused to disappear. Instead, he got a '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the job.',
        sparkWords: ['part-time', 'extremely soggy', 'top-secret'],
      }),
      text(' job at the local '),
      blank({
        id: 'b3',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['ice cream shop', 'fire station', 'aquarium'],
      }),
      text('. His coworkers loved how he could '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['drip', 'wobble', 'whistle'],
      }),
      text(' to keep everyone cool on hot days.'),
    ],
  },
];
