// ----------------------------------------------------------------------------
//  seedLibrary.ts - the hand-written Slice 1 template library
//  (template-model/02-seed-library).
//
//  This is QuibbleStone's tiny, hand-curated content library (README section
//  4 / 7 / 8 - "a tiny hand-written library" is part of the thin vertical
//  slice). Every entry is a plain `Template` object literal built with the
//  `text()` / `blank()` constructors exported from `../engine/template`
//  (template-model/01). This file is PURE DATA - no AI generation, no
//  authoring UI, no back-office content factory (those are explicitly out of
//  scope here; see docs/features/template-model/02-authoring-and-seed-library.md). Adding a
//  new template is a single, documented step: append one object literal to
//  `seedLibrary` below. See ./README.md for the full authoring guide and a
//  copy-paste starter template.
//
//  Story length: every template here carries 9-10 blanks across several
//  sentences. That is deliberate for multiplayer: blanks are dealt
//  round-robin across the roster (../engine/distribute.ts), so a story only
//  gives every player a turn when it has at least as many blanks as there
//  are players - and it only gives everyone SEVERAL turns when it has 2-3x
//  that. Short 4-blank stories left half a 6-player room with nothing to do;
//  do not add new templates below ~8 blanks without a reason.
//
//  Child safety (README section 6): every template here is tagged
//  `tags.familySafe = true` / `tags.ageRating = 'all-ages'` and has been
//  hand-vetted to the SAME bar a player's submitted word must clear at play
//  time (the runtime profanity/safety filter, owned by child-safety/01, is a
//  separate complementary guard for player-submitted free text - this file
//  does not reimplement it; it just makes sure the seed content itself never
//  needs filtering). The humor here comes from absurdity (talking llamas,
//  carsick aliens, a sock-eating dragon), never from innuendo or edge. A few
//  templates (the secret recipe, the fame guide, the new neighbor) are
//  deliberately OPEN-ENDED - the prose leaves room for players to steer the
//  story in several directions - but the authored text itself still clears
//  the all-ages bar; open-ended never means edgy.
//
//  ======================== KEEP THE SERVER MIRROR IN SYNC ====================
//  api/src/Content/TemplateCatalog.cs mirrors this file BY HAND (id,
//  familySafe, blank count). Add / remove / resize a template here and you
//  MUST update that catalog too, or group play will pick templates the client
//  cannot resolve (or deal the wrong number of blanks).
//  ============================================================================
//
//  Who imports this: single-player and group-play (the template picker
//  reads this array today; later it can move behind the API / Table Storage
//  without changing the shape - see the file footer note in ./README.md).
// ----------------------------------------------------------------------------

import { blank, text, type Template } from '../engine/template';

export const seedLibrary: readonly Template[] = [
  {
    id: 'wobbly-wizard',
    title: 'The Wobbly Wizard & the Golden Sock',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['fantasy', 'monsters'] },
    body: [
      text('Once upon a time, a '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the wizard - anything goes!',
        sparkWords: ['wobbly', 'sparkly', 'enormous'],
      }),
      text(' wizard named '),
      blank({
        id: 'b2',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our hero.',
        sparkWords: ['Bartholomew', 'Pickle', 'Zorbo'],
      }),
      text(' lost a magic '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Any object, big or small.',
        sparkWords: ['sock', 'spoon', 'hat'],
      }),
      text(
        '. Without it, every spell went hopelessly wrong: instead of lightning bolts, the wand could only shoot out ',
      ),
      blank({
        id: 'b4',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "pickles".',
        sparkWords: ['pickles', 'feathers', 'meatballs'],
      }),
      text('. To find the missing treasure, the wizard had to '),
      blank({
        id: 'b5',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['waddle', 'juggle', 'sneeze'],
      }),
      text(' all the way to the top of a '),
      blank({
        id: 'b6',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['mountain', 'castle', 'broom closet'],
      }),
      text(', where a '),
      blank({
        id: 'b7',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'Something that describes the troll.',
        sparkWords: ['grumpy', 'glittery', 'very polite'],
      }),
      text(
        ' troll guarded the kingdom\'s lost-and-found box. "You may look inside," the troll rumbled, "but only if you can ',
      ),
      blank({
        id: 'b8',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me another action word',
        subHint: 'A tricky feat to perform for the troll.',
        sparkWords: ['hop on one foot', 'sing opera', 'moonwalk'],
      }),
      text(' while balancing a '),
      blank({
        id: 'b9',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me another thing',
        subHint: 'Something to balance on your head.',
        sparkWords: ['pumpkin', 'teapot', 'bowling ball'],
      }),
      text(' on your head." The wizard did it on the very first try. "'),
      blank({
        id: 'b10',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'An exclamation, like "Yikes!" or "Hooray!"',
        sparkWords: ['Yowza!', 'Holy moly!', 'Ta-da!'],
      }),
      text('" the whole kingdom cheered, and the magic sock was found at last.'),
    ],
  },
  {
    id: 'space-llama',
    title: 'The Space Llama Who Forgot His Helmet',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['space', 'animals'] },
    body: [
      text('Captain '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our space traveler.',
        sparkWords: ['Nibbles', 'Captain Fuzz', 'Dottie'],
      }),
      text(' the llama blasted off in a '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the rocket.',
        sparkWords: ['squeaky', 'glittery', 'lopsided'],
      }),
      text(' rocket made of '),
      blank({
        id: 'b3',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "marshmallows".',
        sparkWords: ['marshmallows', 'bottle caps', 'noodles'],
      }),
      text('. Mission Control had exactly one rule: do NOT touch the big '),
      blank({
        id: 'b4',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'Something that describes a very tempting button.',
        sparkWords: ['red', 'mysterious', 'extra-shiny'],
      }),
      text(" button. Halfway to the moon, the llama's hoof slipped, and the whole rocket started to "),
      blank({
        id: 'b5',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['hiccup', 'somersault', 'hum'],
      }),
      text('. "'),
      blank({
        id: 'b6',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'What Mission Control yells into the radio.',
        sparkWords: ['Abort!', 'Oh no!', 'Not the button!'],
      }),
      text('" yelled Mission Control. Outside the window, '),
      blank({
        id: 'b7',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['7', '42', '1,000'],
      }),
      text(' space goats floated by, calmly munching on '),
      blank({
        id: 'b8',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of another thing',
        subHint: 'A snack for space goats.',
        sparkWords: ['moon rocks', 'cheese puffs', 'antennas'],
      }),
      text(' and refusing to help. Luckily, the rocket landed softly at '),
      blank({
        id: 'b9',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['the moon', 'a trampoline park', "Grandma's roof"],
      }),
      text(
        ', where everyone agreed it was the best crash landing in history and celebrated with a giant ',
      ),
      blank({
        id: 'b10',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Something worth celebrating with.',
        sparkWords: ['cake', 'parade', 'trophy'],
      }),
      text('.'),
    ],
  },
  {
    id: 'road-trip-disaster',
    title: 'The Great Family Road Trip Disaster',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['road-trip', 'family'] },
    body: [
      text('We packed the car with '),
      blank({
        id: 'b1',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['12', '300', '3'],
      }),
      text(' bags of '),
      blank({
        id: 'b2',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "snacks".',
        sparkWords: ['pretzels', 'rubber ducks', 'socks'],
      }),
      text(' and set off toward '),
      blank({
        id: 'b3',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ["Grandma's house", 'the moon', 'Pancake City'],
      }),
      text(
        '. Mom was in charge of directions, Dad was in charge of snacks, and our dog ',
      ),
      blank({
        id: 'b4',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A name for the family dog.',
        sparkWords: ['Waffles', 'Biscuit', 'Sir Barksalot'],
      }),
      text(' was in charge of drooling out the window. After an hour, Dad started to '),
      blank({
        id: 'b5',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['yodel', 'snore', 'beatbox'],
      }),
      text(' so loudly that everyone shouted "'),
      blank({
        id: 'b6',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'An exclamation, like "Whoa!" or "Pull over!"',
        sparkWords: ['Whoa!', 'Pull over!', 'My ears!'],
      }),
      text('" Then the GPS got confused and sent us straight through a '),
      blank({
        id: 'b7',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the car wash.',
        sparkWords: ['extremely bubbly', 'haunted', 'sparkly'],
      }),
      text(
        ' car wash - with the windows down. We stopped for lunch at a roadside diner that only served ',
      ),
      blank({
        id: 'b8',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of another thing',
        subHint: 'The only food on the menu.',
        sparkWords: ['pancakes', 'pickles', 'corn dogs'],
      }),
      text(', where Mom dared the whole family to '),
      blank({
        id: 'b9',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me another action word',
        subHint: 'A dare for the whole family.',
        sparkWords: ['dance', 'cartwheel', 'moo like a cow'],
      }),
      text(' in the parking lot. By the time we finally arrived, the car smelled like '),
      blank({
        id: 'b10',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'A smell, a snack, a mystery - anything.',
        sparkWords: ['wet dog', 'cheese', 'victory'],
      }),
      text(' and nobody cared one bit. Best. Trip. Ever.'),
    ],
    wordBank: [
      { category: 'plural-noun', word: 'pretzels' },
      { category: 'plural-noun', word: 'rubber ducks' },
      { category: 'plural-noun', word: 'corn dogs' },
      { category: 'verb', word: 'yodel' },
      { category: 'verb', word: 'wiggle' },
      { category: 'verb', word: 'cartwheel' },
      { category: 'place', word: 'Pancake City' },
      { category: 'noun', word: 'wet dog' },
      { category: 'name', word: 'Sir Barksalot' },
    ],
  },
  {
    id: 'school-of-noodles',
    title: 'Show and Tell at Noodle Elementary',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['school'] },
    body: [
      text('At school today, '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our classmate.',
        sparkWords: ['Pip', 'Waffles', 'Mortimer'],
      }),
      text(' brought a '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the thing they brought.',
        sparkWords: ['squishy', 'invisible', 'humongous'],
      }),
      text(' '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Any object, big or small.',
        sparkWords: ['kazoo', 'pet rock', 'umbrella'],
      }),
      text(' for show and tell. Our teacher, Ms. '),
      blank({
        id: 'b4',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny last name',
        subHint: "The teacher's name.",
        sparkWords: ['Snodgrass', 'Picklebottom', 'Von Noodle'],
      }),
      text(' raised one eyebrow and asked where it came from. "I found it in '),
      blank({
        id: 'b5',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'Where the mystery item was found.',
        sparkWords: ['a swamp', 'my backpack', "the teachers' lounge"],
      }),
      text(
        '," came the proud answer. Then, right in the middle of the explanation, the thing began to ',
      ),
      blank({
        id: 'b6',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something the mystery item suddenly does.',
        sparkWords: ['glow', 'wiggle', 'sing'],
      }),
      text(' all on its own. The whole class started to '),
      blank({
        id: 'b7',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me another action word',
        subHint: 'How the class reacts.',
        sparkWords: ['giggle', 'applaud', 'dance'],
      }),
      text(', '),
      blank({
        id: 'b8',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['2', '17', '100'],
      }),
      text(' hall monitors burst through the door yelling "'),
      blank({
        id: 'b9',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'What the hall monitors yell.',
        sparkWords: ['Nobody panic!', 'Not again!', 'Hall pass!'],
      }),
      text(
        '", and the fire alarm sang along. The school newspaper called it "the most ',
      ),
      blank({
        id: 'b10',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'How the newspaper described the whole event.',
        sparkWords: ['legendary', 'chaotic', 'magnificent'],
      }),
      text(' show and tell in history" - and honestly, they were right.'),
    ],
  },
  {
    id: 'monster-under-bed',
    title: 'The Monster Under the Bed Needs a Favor',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['monsters'] },
    body: [
      text('Under the bed lived a '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the monster.',
        sparkWords: ['fluffy', 'three-eyed', 'ticklish'],
      }),
      text(' monster named '),
      blank({
        id: 'b2',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our monster.',
        sparkWords: ['Glorp', 'Bubbles', 'Sir Fang'],
      }),
      text(' who really needed to borrow a '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Any object, big or small.',
        sparkWords: ['flashlight', 'pillow', 'banana'],
      }),
      text('. Every night it would '),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['tiptoe', 'giggle', 'tumble'],
      }),
      text(
        ' around the room searching for one, quiet as a whisper. But one night it stubbed its toe on a ',
      ),
      blank({
        id: 'b5',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'Something that describes the skateboard.',
        sparkWords: ['squeaky', 'glow-in-the-dark', 'invisible'],
      }),
      text(' skateboard and hollered "'),
      blank({
        id: 'b6',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'What you yell when you stub your toe.',
        sparkWords: ['Ouchie!', 'Great googly moogly!', 'My toe!'],
      }),
      text(
        '" The kid upstairs sat bolt upright, peeked under the bed, and instead of screaming asked, "Is THIS what you\'ve been looking for?" It turned out the kid had ',
      ),
      blank({
        id: 'b7',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['14', '2', '600'],
      }),
      text(
        ' of them stashed in the closet. Now the two of them are best friends: every night they sneak down to ',
      ),
      blank({
        id: 'b8',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'Their secret nighttime hangout.',
        sparkWords: ['the kitchen', 'the treehouse', 'the couch fort'],
      }),
      text(', share a bowl of '),
      blank({
        id: 'b9',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'A midnight snack.',
        sparkWords: ['crackers', 'marshmallows', 'leftover spaghetti'],
      }),
      text(', and practice how to '),
      blank({
        id: 'b10',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me another action word',
        subHint: 'Something to practice very, very quietly.',
        sparkWords: ['juggle', 'tap-dance', 'howl softly'],
      }),
      text(' without waking the grown-ups.'),
    ],
  },
  {
    id: 'food-truck-frenzy',
    title: 'Grand Opening of the Mystery Food Truck',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['food'] },
    body: [
      text(
        'The new food truck rolled into town with a horn that played circus music and a sign that read: "GRAND OPENING - today only, ',
      ),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the food.',
        sparkWords: ['gooey', 'rainbow', 'crunchy'],
      }),
      text(' '),
      blank({
        id: 'b2',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "pancakes".',
        sparkWords: ['pancakes', 'tacos', 'meatballs'],
      }),
      text(' topped with '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Any topping you can imagine.',
        sparkWords: ['glitter', 'cheese', 'confetti'],
      }),
      text('!" By noon, the line stretched all the way to '),
      blank({
        id: 'b4',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['the library', 'outer space', 'next door'],
      }),
      text('. The chef, a '),
      blank({
        id: 'b5',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'Something that describes the chef.',
        sparkWords: ['cheerful', 'mustachioed', 'seven-foot-tall'],
      }),
      text(' fellow named '),
      blank({
        id: 'b6',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: "The chef's name.",
        sparkWords: ['Chef Marco', 'Gus', 'Frankie Fry'],
      }),
      text(
        ', flipped orders high into the air and caught them behind his back. When the mayor took the very first bite, she began to ',
      ),
      blank({
        id: 'b7',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'What the mayor does out of pure happiness.',
        sparkWords: ['tap-dance', 'weep', 'twirl'],
      }),
      text(' with joy and declared, "'),
      blank({
        id: 'b8',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: "The mayor's official proclamation.",
        sparkWords: ['Delicious!', 'More please!', 'I declare a holiday!'],
      }),
      text('" The truck sold out in exactly '),
      blank({
        id: 'b9',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['8', '90', '3'],
      }),
      text(' minutes, and to this day nobody knows what was actually in the secret sauce.'),
    ],
    wordBank: [
      { category: 'plural-noun', word: 'pancakes' },
      { category: 'plural-noun', word: 'tacos' },
      { category: 'noun', word: 'cheese' },
      { category: 'noun', word: 'glitter' },
      { category: 'place', word: 'the library' },
      { category: 'adjective', word: 'gooey' },
      { category: 'verb', word: 'twirl' },
      { category: 'name', word: 'Frankie Fry' },
    ],
  },
  {
    id: 'backyard-safari',
    title: 'The Backyard Safari Expedition',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['animals'] },
    body: [
      text('Armed with a magnifying glass and a peanut butter sandwich, '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our explorer.',
        sparkWords: ['Indy', 'Professor Pebbles', 'Marisol'],
      }),
      text(' set off to find the rare and '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the creature.',
        sparkWords: ['polka-dotted', 'extremely shy', 'bouncy'],
      }),
      text(' backyard '),
      blank({
        id: 'b3',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me an animal or creature',
        subHint: 'Any critter, real or made up.',
        sparkWords: ['snail', 'squirrel', 'dragonfly'],
      }),
      text('. According to the field guide, it can only be spotted near '),
      blank({
        id: 'b4',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'Somewhere in or near a backyard.',
        sparkWords: ['the garden hose', 'the compost pile', 'a flowerpot'],
      }),
      text(', and only if you '),
      blank({
        id: 'b5',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'How to approach very, very quietly.',
        sparkWords: ['crawl', 'hum', 'tiptoe'],
      }),
      text(' the entire way there. After '),
      blank({
        id: 'b6',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['3', '11', '47'],
      }),
      text(' long hours of searching, there it was at last: sunbathing on a '),
      blank({
        id: 'b7',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'Something that describes the leaf.',
        sparkWords: ['wobbly', 'gigantic', 'fancy'],
      }),
      text(
        ' leaf like it owned the whole yard. The moment it noticed it was being watched, it began to ',
      ),
      blank({
        id: 'b8',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me another action word',
        subHint: 'What the creature does for its audience.',
        sparkWords: ['wave', 'nap', 'do a backflip'],
      }),
      text(' right on cue. "'),
      blank({
        id: 'b9',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'What our explorer whispers in triumph.',
        sparkWords: ['Incredible!', 'Gotcha!', 'Science!'],
      }),
      text(
        '" whispered our explorer, snapping a photo for the Backyard Science Journal. It remains the greatest discovery the neighborhood has ever known.',
      ),
    ],
  },
  {
    id: 'pirate-puddle',
    title: 'Captain Puddlebeard and the Bathtub Treasure',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['pirates', 'fantasy'] },
    body: [
      text('Ahoy! Captain '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our captain.',
        sparkWords: ['Puddlebeard', 'Salty Sam', 'Coral'],
      }),
      text(' sailed the seven bathtubs in search of a '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the treasure.',
        sparkWords: ['shimmering', 'rubbery', 'gigantic'],
      }),
      text(' chest of '),
      blank({
        id: 'b3',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "gummy bears".',
        sparkWords: ['gummy bears', 'bath toys', 'bubbles'],
      }),
      text('. The treasure map was drawn in crayon and smelled faintly of '),
      blank({
        id: 'b4',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'A mysterious smell for a mysterious map.',
        sparkWords: ['bubble gum', 'shampoo', 'old cheese'],
      }),
      text('. To reach the loot, the crew had to '),
      blank({
        id: 'b5',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['splash', 'sing', 'paddle'],
      }),
      text(' past the dreaded Soap Kraken, a beast with '),
      blank({
        id: 'b6',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'How many slippery arms the Kraken has.',
        sparkWords: ['8', '23', '500'],
      }),
      text(' slippery arms. First mate '),
      blank({
        id: 'b7',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me another funny name',
        subHint: "The first mate's name.",
        sparkWords: ['Squeaky', 'Barnacle Betty', 'Duckie'],
      }),
      text(' bravely distracted it by starting to '),
      blank({
        id: 'b8',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me another action word',
        subHint: 'A very loud distraction.',
        sparkWords: ['yodel', 'blow bubbles', 'do the backstroke'],
      }),
      text(' at the top of their lungs. The Kraken was so flustered that it hid behind '),
      blank({
        id: 'b9',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'Somewhere a giant Kraken could (almost) hide.',
        sparkWords: ['the shower curtain', 'a lighthouse', 'the deep end'],
      }),
      text(' and refused to come out. "'),
      blank({
        id: 'b10',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'An exclamation, like "Arr!" or "Land ho!"',
        sparkWords: ['Arr!', 'Land ho!', 'Splashtastic!'],
      }),
      text(
        '" the captain bellowed as the chest popped open, and the crew celebrated with a twenty-one bubble-cannon salute.',
      ),
    ],
  },
  {
    id: 'robot-recital',
    title: 'The Robot Who Joined the School Talent Show',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['school', 'sci-fi'] },
    body: [
      text('A '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the robot.',
        sparkWords: ['clanky', 'shiny', 'tiny'],
      }),
      text(' robot named '),
      blank({
        id: 'b2',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our robot.',
        sparkWords: ['Beep-Bop', 'Gearald', 'Sprocket'],
      }),
      text(' signed up for the school talent show, promising to '),
      blank({
        id: 'b3',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO on stage.',
        sparkWords: ['tap-dance', 'juggle', 'yodel'],
      }),
      text(' in front of the whole school. Backstage, it oiled its joints, polished its '),
      blank({
        id: 'b4',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'A robot accessory worth polishing.',
        sparkWords: ['antenna', 'tuba', 'bow tie'],
      }),
      text(' until it gleamed, and ran '),
      blank({
        id: 'b5',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['50', '6', '999'],
      }),
      text(
        ' practice drills. But the moment the spotlight hit, something went BZZZT: the robot short-circuited and started to ',
      ),
      blank({
        id: 'b6',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me another action word',
        subHint: 'What the robot does instead of its act.',
        sparkWords: ['breakdance', 'beep the alphabet', 'do the robot'],
      }),
      text(' instead. Confetti and '),
      blank({
        id: 'b7',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "sparks".',
        sparkWords: ['sparks', 'bolts', 'balloons'],
      }),
      text(' shot out of its ears and rained down on the crowd. The audience went completely '),
      blank({
        id: 'b8',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'How the crowd reacted.',
        sparkWords: ['bananas', 'wild', 'giddy'],
      }),
      text(', leapt to their feet, and roared "'),
      blank({
        id: 'b9',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'What the crowd roars.',
        sparkWords: ['Encore!', 'Best show ever!', 'Beep beep hooray!'],
      }),
      text('" The robot took a bow, sparked twice, and was voted the winner by a landslide.'),
    ],
  },
  {
    id: 'dragon-sock-thief',
    title: 'The Dragon Who Only Eats Mismatched Socks',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['monsters', 'fantasy'] },
    body: [
      text('Deep in a '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the cave.',
        sparkWords: ['cozy', 'sparkly', 'squeaky'],
      }),
      text(' cave lived a dragon named '),
      blank({
        id: 'b2',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: "The dragon's name.",
        sparkWords: ['Cinder', 'Snackster', 'Lord Puff'],
      }),
      text(' who only ate mismatched '),
      blank({
        id: 'b3',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Plural objects, e.g. "socks".',
        sparkWords: ['socks', 'mittens', 'flip-flops'],
      }),
      text('. Every night it would sneak into '),
      blank({
        id: 'b4',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['the laundry room', 'a sleepover', 'the dryer'],
      }),
      text(' and '),
      blank({
        id: 'b5',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['tiptoe', 'sniff around', 'pounce'],
      }),
      text(' until it found a tasty pair. One evening, it got its tail stuck in a '),
      blank({
        id: 'b6',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Something a dragon tail could get stuck in.',
        sparkWords: ['laundry basket', 'vacuum cleaner', 'beanbag chair'],
      }),
      text(' and had to '),
      blank({
        id: 'b7',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me another action word',
        subHint: 'How to escape without waking anyone.',
        sparkWords: ['wiggle', 'karate-chop', 'sweet-talk'],
      }),
      text(' its way out before anyone woke up. Back home, it kept a hoard of '),
      blank({
        id: 'b8',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['31', '8', '5,000'],
      }),
      text(' flavors sorted by smell, from "gym class" all the way to "'),
      blank({
        id: 'b9',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'A flavor of cheese, apparently.',
        sparkWords: ['stinky', 'fancy', 'mysterious'],
      }),
      text(' cheese". "'),
      blank({
        id: 'b10',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'An exclamation, like "Yum!" or "Found one!"',
        sparkWords: ['Yum!', 'Found one!', 'Sock-tastic!'],
      }),
      text(
        '" it would rumble happily after every midnight snack, blowing one perfect smoke ring shaped like a sock.',
      ),
    ],
  },
  {
    id: 'birthday-balloon-mayhem',
    title: 'The Birthday Party That Floated Away',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['family', 'birthday'] },
    body: [
      text('At '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our birthday star.',
        sparkWords: ['Sunny', 'Biscuit', 'Theo'],
      }),
      text("'s birthday party, someone brought "),
      blank({
        id: 'b2',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['1,000', '15', '88'],
      }),
      text(' '),
      blank({
        id: 'b3',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the balloons.',
        sparkWords: ['enormous', 'squeaky', 'glittery'],
      }),
      text(
        ' balloons and tied every single one to the cake. Nobody thought this was a problem until the wind began to ',
      ),
      blank({
        id: 'b4',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something the wind does.',
        sparkWords: ['whistle', 'swirl', 'tug'],
      }),
      text(
        '. The cake lifted off the table, hovered over the punch bowl, and sailed away toward ',
      ),
      blank({
        id: 'b5',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['the treetops', 'the moon', 'next door'],
      }),
      text('. All the guests grabbed '),
      blank({
        id: 'b6',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Cake-rescue equipment.',
        sparkWords: ['butterfly nets', 'pool noodles', 'umbrellas'],
      }),
      text(' and gave chase, with the birthday kid out front yelling "'),
      blank({
        id: 'b7',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'A birthday battle cry.',
        sparkWords: ['After that cake!', 'Not the frosting!', 'Charge!'],
      }),
      text('" In the end, Uncle '),
      blank({
        id: 'b8',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me another funny name',
        subHint: "The heroic uncle's name.",
        sparkWords: ['Marv', 'Tito', 'Bob'],
      }),
      text(' saved the day by climbing a '),
      blank({
        id: 'b9',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'Something that describes the ladder.',
        sparkWords: ['wobbly', 'twelve-foot', 'borrowed'],
      }),
      text(' ladder and hooking the cake back down with a '),
      blank({
        id: 'b10',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'An improvised cake-rescue hook.',
        sparkWords: ['fishing pole', 'candy cane', 'back scratcher'],
      }),
      text(
        '. The cake was dented and the frosting was windblown, and everyone agreed it was the most delicious rescue in birthday history.',
      ),
    ],
  },
  {
    id: 'snowman-summer-job',
    title: 'The Snowman Who Got a Summer Job',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['seasons', 'monsters'] },
    body: [
      text('When the snow melted, '),
      blank({
        id: 'b1',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'A first name for our snowman.',
        sparkWords: ['Frosty Jr.', 'Chilly', 'Sir Slush'],
      }),
      text(' the snowman refused to disappear. Instead, he printed '),
      blank({
        id: 'b2',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'How many copies of his resume he printed.',
        sparkWords: ['75', '4', '200'],
      }),
      text(' copies of his resume and landed a '),
      blank({
        id: 'b3',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a silly describing word',
        subHint: 'Something that describes the job.',
        sparkWords: ['part-time', 'extremely soggy', 'top-secret'],
      }),
      text(' job at the local '),
      blank({
        id: 'b4',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'A location, real or made up.',
        sparkWords: ['ice cream shop', 'fire station', 'aquarium'],
      }),
      text('. His boss was nervous at first: after all, an employee who can '),
      blank({
        id: 'b5',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Something you DO.',
        sparkWords: ['drip', 'wobble', 'whistle'],
      }),
      text(
        ' during every shift does not come along every day. But the customers adored him, especially when he juggled ',
      ),
      blank({
        id: 'b6',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Something cold to juggle.',
        sparkWords: ['ice cubes', 'popsicles', 'snowballs'],
      }),
      text(
        ' to keep everyone cool on hot afternoons. By August he was named Employee of the Month, and the mayor gave a ',
      ),
      blank({
        id: 'b7',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: "Something that describes the mayor's speech.",
        sparkWords: ['tearful', 'five-hour', 'magnificent'],
      }),
      text(' speech in his honor, ending with a mighty "'),
      blank({
        id: 'b8',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: "The mayor's big finish.",
        sparkWords: ['Three cheers!', 'Stay frosty!', 'Hip hip hooray!'],
      }),
      text('" His secret to surviving the heat? He keeps a spare '),
      blank({
        id: 'b9',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'A snowman spare part.',
        sparkWords: ['nose', 'hat', 'mitten'],
      }),
      text(' in the freezer, just in case of heat waves.'),
    ],
  },
  {
    id: 'grandmas-secret-recipe',
    title: "Grandma's Top-Secret Recipe",
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['food', 'family', 'mystery'] },
    body: [
      text("Nobody knows exactly what goes into Grandma's famous "),
      blank({
        id: 'b1',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'The main ingredient - or is it?',
        sparkWords: ['mushroom', 'jellybean', 'meatloaf'],
      }),
      text(' surprise: the recipe lives in a locked '),
      blank({
        id: 'b2',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a describing word',
        subHint: 'Something that describes the box under her bed.',
        sparkWords: ['dusty', 'glowing', 'triple-locked'],
      }),
      text(
        ' box under her bed. Family legend says she traded for it long ago with a mysterious stranger at ',
      ),
      blank({
        id: 'b3',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'Anywhere a mysterious trade might happen.',
        sparkWords: ['a carnival', 'the crossroads', 'a yard sale'],
      }),
      text(', who whispered these exact words: "Add '),
      blank({
        id: 'b4',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['3', '12', '99'],
      }),
      text(' cups of '),
      blank({
        id: 'b5',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'A secret ingredient - anything at all.',
        sparkWords: ['raisins', 'gummy worms', 'onions'],
      }),
      text('. Then '),
      blank({
        id: 'b6',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'A cooking move - or any move.',
        sparkWords: ['stir', 'whisk', 'shake'],
      }),
      text(' the mixture gently until it begins to '),
      blank({
        id: 'b7',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me another action word',
        subHint: 'What the mixture does when it is ready.',
        sparkWords: ['bubble', 'hum', 'glow'],
      }),
      text('. Serve it '),
      blank({
        id: 'b8',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'How the dish must be served.',
        sparkWords: ['cold', 'sizzling', 'upside-down'],
      }),
      text(
        ', and never, EVER, tell anyone what you saw." Every holiday, someone begs Grandma for the secret. Every holiday, she just smiles sweetly and says, "',
      ),
      blank({
        id: 'b9',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: "Grandma's answer to anyone who asks.",
        sparkWords: ['Nice try!', 'Over my rolling pin!', 'Ha!'],
      }),
      text('" The only other living soul who knows the truth is her parrot, '),
      blank({
        id: 'b10',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: "The parrot's name.",
        sparkWords: ['Crackers', 'Pepper', 'Admiral Beaky'],
      }),
      text(', and the parrot has been bribed with crackers.'),
    ],
  },
  {
    id: 'how-to-be-famous',
    title: 'How to Become Famous in Five Easy Steps',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['fame', 'how-to'] },
    body: [
      text(
        'So you want to be famous? Follow this official guide. Step one: discover your talent, like being able to ',
      ),
      blank({
        id: 'b1',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'Your world-class talent.',
        sparkWords: ['whistle', 'limbo', 'speed-knit'],
      }),
      text(' while balancing a '),
      blank({
        id: 'b2',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'Something to balance on your nose.',
        sparkWords: ['spoon', 'goldfish bowl', 'birthday cake'],
      }),
      text(' on your nose. Step two: pick an unforgettable stage name, something like "'),
      blank({
        id: 'b3',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: 'Your dazzling stage name.',
        sparkWords: ['Ziggy', 'The Great Dini', 'Momo'],
      }),
      text(' the '),
      blank({
        id: 'b4',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a describing word',
        subHint: 'The second half of your stage name.',
        sparkWords: ['Magnificent', 'Unstoppable', 'Slightly Dizzy'],
      }),
      text('". Step three: practice in front of your '),
      blank({
        id: 'b5',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'Your very first (captive) audience.',
        sparkWords: ['houseplants', 'goldfish', 'stuffed animals'],
      }),
      text(' until they stop wandering off. Step four: book your first big show at '),
      blank({
        id: 'b6',
        category: 'place',
        categoryLabel: 'PLACE',
        prompt: 'Give me a place',
        subHint: 'The venue of your debut.',
        sparkWords: ['the garage', 'a stadium', 'the bus stop'],
      }),
      text(' and invite exactly '),
      blank({
        id: 'b7',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'The size of your crowd.',
        sparkWords: ['9', '80,000', '2'],
      }),
      text(' people. Step five: when the crowd goes wild, shout "'),
      blank({
        id: 'b8',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'Your signature catchphrase.',
        sparkWords: ['Thank you, everybody!', 'Kaboom!', 'You are all beautiful!'],
      }),
      text('", take a bow, and toss '),
      blank({
        id: 'b9',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of another thing',
        subHint: 'Something to shower on your adoring fans.',
        sparkWords: ['roses', 'ping-pong balls', 'coupons'],
      }),
      text(
        ' into the audience. Warning: fame may cause autographs, paparazzi, and one extremely ',
      ),
      blank({
        id: 'b10',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'Something that describes your fan club.',
        sparkWords: ['devoted', 'noisy', 'confused'],
      }),
      text(' fan club. Good luck out there, superstar.'),
    ],
  },
  {
    id: 'the-new-neighbor',
    title: 'The New Neighbor Nobody Has Met',
    tags: { familySafe: true, ageRating: 'all-ages', themes: ['mystery', 'neighborhood'] },
    body: [
      text('Someone finally moved into the '),
      blank({
        id: 'b1',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me a describing word',
        subHint: 'Something that describes the house at the end of the street.',
        sparkWords: ['creaky', 'lavender', 'mysterious'],
      }),
      text(
        ' house at the end of our street, but nobody has actually seen them. The mail carrier says they receive ',
      ),
      blank({
        id: 'b2',
        category: 'number',
        categoryLabel: 'NUMBER',
        prompt: 'Give me a number',
        subHint: 'Any number you like.',
        sparkWords: ['17', '4', '250'],
      }),
      text(' packages a day, every single one of them shaped like '),
      blank({
        id: 'b3',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of a thing',
        subHint: 'The shape of the mystery packages.',
        sparkWords: ['trombones', 'birdcages', 'garden gnomes'],
      }),
      text(
        '. At exactly midnight, a sound drifts out of the chimney: something halfway between a ',
      ),
      blank({
        id: 'b4',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me a thing',
        subHint: 'The first half of the mystery sound.',
        sparkWords: ['foghorn', 'music box', 'walrus'],
      }),
      text(' and a '),
      blank({
        id: 'b5',
        category: 'noun',
        categoryLabel: 'NOUN',
        prompt: 'Give me another thing',
        subHint: 'The second half of the mystery sound.',
        sparkWords: ['kazoo', 'thunderstorm', 'teakettle'],
      }),
      text('. My best friend '),
      blank({
        id: 'b6',
        category: 'name',
        categoryLabel: 'NAME',
        prompt: 'Give me a funny name',
        subHint: "Your best friend's name.",
        sparkWords: ['Josie', 'Marcus', 'Petey'],
      }),
      text(' swears they once saw the neighbor '),
      blank({
        id: 'b7',
        category: 'verb',
        categoryLabel: 'VERB',
        prompt: 'Give me an action word',
        subHint: 'What the neighbor was doing on the roof.',
        sparkWords: ['cartwheel', 'glide', 'tap-dance'],
      }),
      text(
        ' across the roof in the moonlight. So we did what any brave kids would do: we baked cookies, marched up the ',
      ),
      blank({
        id: 'b8',
        category: 'adjective',
        categoryLabel: 'ADJECTIVE',
        prompt: 'Give me another describing word',
        subHint: 'Something that describes the driveway.',
        sparkWords: ['winding', 'moonlit', 'extremely long'],
      }),
      text(' driveway, and rang the doorbell. The door creaked open, and a warm voice said, "'),
      blank({
        id: 'b9',
        category: 'exclamation',
        categoryLabel: 'EXCLAMATION',
        prompt: 'Give me something you shout',
        subHint: 'The first thing the neighbor says.',
        sparkWords: ['At last!', 'Welcome, welcome!', 'Oh, happy day!'],
      }),
      text(' I was hoping someone would finally visit. Come in - do you like '),
      blank({
        id: 'b10',
        category: 'plural-noun',
        categoryLabel: 'PLURAL NOUN',
        prompt: 'Give me more than one of another thing',
        subHint: "The neighbor's favorite thing to share.",
        sparkWords: ['cookies', 'riddles', 'board games'],
      }),
      text('?"'),
    ],
  },
];
